// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

type AnnouncementListRsp struct {
	ID        uint   `json:"id"`
	Title     string `json:"title"`
	Content   string `json:"content"`
	Type      uint8  `json:"type"`
	Status    uint8  `json:"status"`
	Cover     string `json:"cover"`
	CreatedAt string `json:"created_at"`
	UpdatedAt string `json:"updated_at"`
}

type AnnouncementListRst struct {
}

type CategoriesListRsp struct {
	ID        uint   `json:"id"`
	Name      string `json:"name"`
	Url       string `json:"url"`
	Count     uint   `json:"count"`
	Icon      string `json:"icon"`
	Gradient  string `json:"gradient"`
	UpdatedAt string `json:"updated_at"`
	CreatedAt string `json:"created_at"`
}

type CategoriesListRst struct {
}

type RecentDownloadWallpaperRsp struct {
	WallpaperList []WallpaperListRsp `json:"wallpaper_list"`
}

type RecentDownloadWallpaperRst struct {
}

type RecommendWallpaper struct {
	ID            uint   `json:"id"`
	Title         string `json:"title"`
	Url           string `json:"url"`
	LikeCount     uint   `json:"like_count"`
	DownloadCount uint   `json:"download_count"`
	CollectCount  uint   `json:"collect_count"`
	ViewCount     uint   `json:"view_count"`
}

type RecommendWallpaperRsp struct {
	RecommendList []RecommendWallpaper `json:"recommend_list"`
	NewList       []RecommendWallpaper `json:"new_list"`
	HotList       []RecommendWallpaper `json:"hot_list"`
	SelectedList  []RecommendWallpaper `json:"selected_list"`
}

type RecommendWallpaperRst struct {
}

type RefreshTokenRsp struct {
	Token        string `json:"token"`
	RefreshToken string `json:"refresh_token"`
	ExpireAt     int64  `json:"expire_at"`
}

type RefreshTokenRst struct {
	RefreshToken string `json:"refresh_token"`
}

type SearchWallpaperRsp struct {
	WallpaperList []WallpaperListRsp `json:"wallpaper_list"`
}

type SearchWallpaperRst struct {
	Keyword  string `form:"keyword"`
	Page     int    `form:"page, default=1"`
	PageSize int    `form:"page_size, default=10, range=[1:50]"`
}

type UpdateUserInfoRsp struct {
}

type UpdateUserInfoRst struct {
	UserName  string `json:"username, optional"`
	AvatarUrl string `json:"avatar_url, optional"`
	Phone     string `json:"phone, optional"`
}

type UploadOssTokenRsp struct {
	Token string `json:"token"`
	Url   string `json:"url"`
	Key   string `json:"key"`
}

type UploadOssTokenRst struct {
	TypeKey string `form:"type,options=avatar"`
	Format  string `form:"format,options=jpg,png,jpeg"`
}

type UserClickOperationCheckRsp struct {
	IsLike     bool `json:"is_like"`
	IsCollect  bool `json:"is_collect"`
	IsDownload bool `json:"is_download"`
}

type UserClickOperationCheckRst struct {
	WallpaperId uint `form:"id"`
}

type UserClickOperationCountRsp struct {
	LikeCount     int64 `json:"like_count"`
	CollectCount  int64 `json:"collect_count"`
	DownloadCount int64 `json:"download_count"`
}

type UserClickOperationCountRst struct {
}

type UserClickOperationRsp struct {
}

type UserClickOperationRst struct {
	WallpaperId   uint64 `json:"id"`
	Operation     string `json:"operation,options=like|collect|download"`
	OperationType int    `json:"operation_type,options=1|2, default=1"`
}

type UserClickOperationWallpaperRsp struct {
	WallpaperList []WallpaperListRsp `json:"wallpaper_list"`
}

type UserClickOperationWallpaperRst struct {
	Operation string `form:"operation,options=like|collect|download"`
	Page      int    `form:"page, default=1"`
	PageSize  int    `form:"page_size, default=10, range=[1:50]"`
}

type WallpaperDetailRsp struct {
	ID            uint                 `json:"id"`
	Title         string               `json:"title"`
	Url           string               `json:"url"`
	CleanUrl      string               `json:"clean_url"`
	LikeCount     uint                 `json:"like_count"`
	DownloadCount uint                 `json:"download_count"`
	CollectCount  uint                 `json:"collect_count"`
	ViewCount     uint                 `json:"view_count"`
	CreatedAt     string               `json:"created_at"`
	Classify      string               `json:"classify"`
	RecommendList []RecommendWallpaper `json:"recommend_list"`
}

type WallpaperDetailRst struct {
	ID uint `form:"id"`
}

type WallpaperListRsp struct {
	ID            uint   `json:"id"`
	Title         string `json:"title"`
	Url           string `json:"url"`
	LikeCount     uint   `json:"like_count"`
	DownloadCount uint   `json:"download_count"`
	CollectCount  uint   `json:"collect_count"`
	ViewCount     uint   `json:"view_count"`
}

type WallpaperListRst struct {
	ClassifyId uint `form:"classify_id"`
	Page       int  `form:"page, default=1"`
	PageSize   int  `form:"page_size, default=10, range=[1:50]"`
}

type WxLoginCodeRsp struct {
	ID           uint   `json:"id"`
	Token        string `json:"token"`
	RefreshToken string `json:"refresh_token"`
	UserName     string `json:"username"`
	AvatarUrl    string `json:"avatar_url"`
	Phone        string `json:"phone"`
	ExpireAt     int64  `json:"expire_at"`
}

type WxLoginCodeRst struct {
	Code string `json:"code"`
}

type WxUserInfoRsp struct {
	ID        uint   `json:"id"`
	UserName  string `json:"username"`
	AvatarUrl string `json:"avatar_url"`
	Phone     string `json:"phone"`
}

type WxUserInfoRst struct {
}
