// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package handler

import (
	"net/http"

	common "wallpaper/internal/handler/common"
	login "wallpaper/internal/handler/login"
	mp "wallpaper/internal/handler/mp"
	"wallpaper/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/announcement/list",
				Handler: common.AnnouncementListHandler(serverCtx),
			},
		},
		rest.WithPrefix("/common"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/mp/code",
				Handler: login.WxLoginCodeHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/mp/refresh/token",
				Handler: login.RefreshTokenHandler(serverCtx),
			},
		},
		rest.WithPrefix("/login"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/categories/list",
				Handler: mp.CategoriesListHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/oss/token",
				Handler: mp.UploadOssTokenHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/recommend/wallpaper",
				Handler: mp.RecommendWallpaperHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/search/wallpaper",
				Handler: mp.SearchWallpaperHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/user/click/operation",
				Handler: mp.UserClickOperationHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/user/click/operation/check",
				Handler: mp.UserClickOperationCheckHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/user/click/operation/count",
				Handler: mp.UserClickOperationCountHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/user/click/operation/wallpaper",
				Handler: mp.UserClickOperationWallpaperHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/user/recent/download/wallpaper",
				Handler: mp.RecentDownloadWallpaperHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/userinfo",
				Handler: mp.WxUserInfoHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/userinfo",
				Handler: mp.UpdateUserInfoHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/wallpaper/detail",
				Handler: mp.WallpaperDetailHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/wallpaper/list",
				Handler: mp.WallpaperListHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/mp"),
	)
}
